### PR TITLE
Rarcif issue 48

### PR DESCRIPTION
**Pull request by rarcif**
Issue 48 Solve: tested and integrated complete devnet guide to start 2 devnet nodes.

### CODE REVIEW

**Comment by kether-c** [comment]
I followed the new steps, but encountered an error after run `$ pystarport serve --config ./scripts/cronos-devnet.yaml`
Error message: `AssertionError: /bin/sh: cronosd: command not found
 (cronosd init node0 --chain-id cronos_777-1 --home data/cronos_777-1/node0)`

**Comment by rarcif** [comment]
> I followed the new steps, but encountered an error after run `$ pystarport serve --config ./scripts/cronos-devnet.yaml` Error message: `AssertionError: /bin/sh: cronosd: command not found (cronosd init node0 --chain-id cronos_777-1 --home data/cronos_777-1/node0)`

I checked the file and I noticed that there have been some changes to the cronos-devnet.yaml. These changes are affecting the way pystaport runs the script. For example, by removing the affected lines as per screenshot, the script should be starting the nodes normally. The lines that are commented out need to be looked at by the team that works on the [cronos](https://github.com/crypto-org-chain/cronos) repository to make sure that any variables are being accepted and imported into the yaml file. 
Right now pystaport fails to read these env vars, and as a result fails to start.

Screenshot 2021-12-17 at 08 46 31

**Comment by yihuang** [comment]
You just need to upgrade pystarport to 0.2.3

**Comment by lezzokafka** [comment]
closed via #143, thanks for the joint work from @rarcif and @vincentysc!

**Pull request closed without merging**
