### PR TITLE
GitBook: [#1] Cronos Play Unreal Plugin v0.0.9-alpha Updates

### PR DESCRIPTION
**Pull request by damoncro**

### CODE REVIEW

**Comment by damoncro** [comment]
v0.0.9-alpha is not available in marketplace yet, we could wait it to be approved first before merging.

**Comment by damoncro** [comment]
Just checked v0.0.9-alpha was updated on marketplace! This PR is ready to be merged.

**Review by tomtau — APPROVED** [review]
for walletconnect, is there a way to have a callback for walletconnect changes in blueprint (is it that "out" output or there are walletconnect-specific events)? it'll be good to document it (whether or how it works), perhaps not in this PR but a follow up

**Comment by damoncro** [comment]
@tomtau events can be notified in callbacks in c++ by UE_LOG and events: https://github.com/cronos-labs/play-unreal-plugin/blob/main/Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp#L347-L390. It should work on blueprint, but not tested.

**Comment by leejw51crypto** [comment]
walletconnect event is fired in unreal delegate, now.

**Review by leejw51crypto — APPROVED** [review]

**Review by lezzokafka — APPROVED** [review]

**Pull request merged**
